packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19.2.0"
  react-dom: "^19.1.0"
  next: "^16.0.1"
  tailwindcss: "^4.1.5"
  postcss: "^8.5.3"
  autoprefixer: "^10.4.20"
  typescript: "5.9.2"
  "lucide-react": "^0.554.0"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.1"
  "@types/node": "^22.15.30"
  "@tailwindcss/postcss": "^4.1.5"
  "@tailwindcss/cli": "^4.1.5"
  lexical: "^0.39.0"
  "@lexical/headless": "^0.39.0"
  "@lexical/react": "^0.39.0"
  "@lexical/html": "^0.39.0"
  "@lexical/rich-text": "^0.39.0"
  "@lexical/link": "^0.39.0"
  "@lexical/history": "^0.39.0"
  "@lexical/plain-text": "^0.39.0"
  "@lexical/selection": "^0.39.0"
  "@lexical/utils": "^0.39.0"
  "tailwind-merge": "^3.4.0"
  "uuid": "^13.0.0"
  "@base-ui-components/react": "1.0.0-rc.0"