/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as CustomRouteImport } from "./routes/custom";
import { Route as EditorRouteImport } from "./routes/editor";
import { Route as PreviewRouteImport } from "./routes/preview";

const PreviewRoute = PreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => rootRouteImport,
} as any);
const EditorRoute = EditorRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => rootRouteImport,
} as any);
const CustomRoute = CustomRouteImport.update({
  id: "/custom",
  path: "/custom",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/custom": typeof CustomRoute;
  "/editor": typeof EditorRoute;
  "/preview": typeof PreviewRoute;
}
export interface FileRoutesByTo {
  "/custom": typeof CustomRoute;
  "/editor": typeof EditorRoute;
  "/preview": typeof PreviewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/custom": typeof CustomRoute;
  "/editor": typeof EditorRoute;
  "/preview": typeof PreviewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/custom" | "/editor" | "/preview";
  fileRoutesByTo: FileRoutesByTo;
  to: "/custom" | "/editor" | "/preview";
  id: "__root__" | "/custom" | "/editor" | "/preview";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  CustomRoute: typeof CustomRoute;
  EditorRoute: typeof EditorRoute;
  PreviewRoute: typeof PreviewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/preview": {
      id: "/preview";
      path: "/preview";
      fullPath: "/preview";
      preLoaderRoute: typeof PreviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/editor": {
      id: "/editor";
      path: "/editor";
      fullPath: "/editor";
      preLoaderRoute: typeof EditorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/custom": {
      id: "/custom";
      path: "/custom";
      fullPath: "/custom";
      preLoaderRoute: typeof CustomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  CustomRoute: CustomRoute,
  EditorRoute: EditorRoute,
  PreviewRoute: PreviewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
